version: "3.7"

services:

  jenkins:
    image: jenkins/jenkins:lts
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST
      - LETSENCRYPT_EMAIL
    ports:
      - 8080:8080
      - 5000:5000
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  default:
    external:
      name: nginx-proxy

volumes:
  jenkins_home:
