version: "3.7"

services:

  jenkins.rdok.dev:
    build:
      context: .
      args:
        - DOCKER_GID
    container_name: jenkins.rdok.dev
    image: jenkins.rdok.dev
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST
      - LETSENCRYPT_EMAIL
      - TZ=Europe/London
    ports:
      - 8080:8080
      - 5000:5000
      - 50000:50000
    volumes:
      - jenkins.rdok.dev:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /usr/bin/docker:/usr/bin/docker
      - /usr/local/bin/docker-compose:/usr/local/bin/docker-compose

networks:
  default:
    external:
      name: nginx-proxy

volumes:
  jenkins.rdok.dev:
